# -*- coding: utf-8 -*-
"""
Created on Mon Nov  4 18:06:54 2019

@author: seongpar
"""

SP_Rating = {   'AAA' : 1 ,
                'AA+' : 2 ,
                'AA' : 2 ,
                'AA-' : 2 ,
                'A+' : 3 ,
                'A' : 3 ,
                'A-' : 3 ,
                'BBB+' : 4 ,
                'BBB' : 4 ,
                'BBB-' : 4 ,
                'BB+' : 5 ,
                'BB' : 5 ,
                'BB-' : 5 ,
                'B+' : 6 ,
                'B' : 6 ,
                'B-' : 6 ,
                'CCC+' : 7 ,
                'CCC' : 7 ,
                'CCC-' : 7 ,
                'CC' : 8 ,
                'D' : 8 ,
                'NR' : 0 
                }


Moodys_Rating = {   'Aaa' : 1 ,
                    'Aa1' : 2 ,
                    'Aa2' : 2 ,
                    'Aa3' : 2 ,
                    'A1' : 3 ,
                    'A2' : 3 ,
                    'A3' : 3 ,
                    'Baa1' : 4 ,
                    'Baa2' : 4 ,
                    'Baa3' : 4 ,
                    'Ba1' : 5 ,
                    'Ba2' : 5 ,
                    'Ba3' : 5 ,
                    'B1' : 6 ,
                    'B2' : 6 ,
                    'B3' : 6 ,
                    'Caa1' : 7 ,
                    'Caa2' : 7 ,
                    'Caa3' : 7 ,
                    'Ca' : 8 ,
                    'C' : 8 ,
                    'WR' : 0 ,
                    'NR' : 0 
                    }

Fitch_Rating = {    'AAA' : 1 ,
                    'AA+' : 2 ,
                    'AA' : 2 ,
                    'AA-' : 2 ,
                    'A+' : 3 ,
                    'A' : 3 ,
                    'A-' : 3 ,
                    'BBB+' : 4 ,
                    'BBB' : 4 ,
                    'BBB-' : 4 ,
                    'BB+' : 5 ,
                    'BB' : 5 ,
                    'BB-' : 5 ,
                    'B+' : 6 ,
                    'B' : 6 ,
                    'B-' : 6 ,
                    'CCC+' : 7 ,
                    'CCC' : 7 ,
                    'CCC-' : 7 ,
                    'C' : 8 ,
                    'D' : 8 ,
                    'CC' : 8 ,
                    'WD' : 0 ,
                    'NR' : 0 
        }

AIG_Rating = {  'AAA' : 1 ,
                'AA' : 2 ,
                'A' : 3 ,
                'BBB' : 4 ,
                'BB' : 5 ,
                'B' : 6 ,
                'CCC' : 7 ,
                'CC' : 8 ,
                'C' : 8 ,
                'D' : 8 ,
                'NR' : 8 ,
                'NA' : 8 
        }

AC_Mapping_to_BMA = {   'ABS'                       : 'CMBS' ,
                        'Bank Loan'                 : 'Bonds' ,
                        'CDO'                       : 'Bonds' ,
                        'CMBS Agency'               : 'CMBS' ,
                        'CMBS Non-Agency'           : 'CMBS' ,
                        'Cash'                      : 'Bonds Cash and Govt' ,
                        'Cash Fund'                 : 'Bonds Cash and Govt' ,
                        'Short Term Securities'     : 'Bonds Cash and Govt' ,
                        'Term Deposit'              : 'Bonds Cash and Govt' ,
                        'Collateral Loan'           : 'Other Commercial and Farm Mortgages' ,
                        'Commercial Mortgage Loan'  : 'Other Commercial and Farm Mortgages' ,
                        'Common Equity'             : 'Alternatives' ,
                        'Corporate Bond'            : 'Bonds' ,
                        'Credit Loan'               : 'Bonds' ,
                        'Derivative'                : 'Derivative' ,
                        'Hedge Fund'                : 'Alternatives' ,
                        'Mezzanine Mortgage Loan'   : 'Other Commercial and Farm Mortgages' ,
                        'National Govt'             : 'Bonds Cash and Govt' ,
                        'Other Invested Assets'     : 'Alternatives' ,
                        'Private Equity Fund'       : 'Alternatives' ,
                        'RMBS Agency'               : 'RMBS' ,
                        'RMBS Non-Agency'           : 'RMBS' ,
                        'Regional Govt'             : 'Bonds' ,
                        'Supranational'             : 'Bonds Cash and Govt' ,
                        'Residential Mortgage Loan' : 'Other Residential Mortgages' ,
                        'Consumer Loan'             : 'Policy Loan' ,
                        'ALBA_Hedge'                : 'Derivative' 
        }

Legal_Entity = {'Owning Entity Name': {0: 'American General Life Insurance Company',
                  1: 'The United States Life Insurance Company in the City of New York',
                  2: 'The Variable Annuity Life Insurance Company',
                  3: 'National Union Fire Insurance Company of Pittsburgh, Pa.',
                  4: 'Lexington Insurance Company',
                  5: 'American Home Assurance Company',
                  6: 'Fortitude Reinsurance Company Ltd.',
                  7: 'American International Reinsurance Company, Ltd.',
                  8: 'USLSAMRE',
                  9: 'VALSAMRE',
                  10: 'AHSAMRE',
                  11: 'AGLSAMRE',
                  12: 'AGLSAMRE DTC'},
                 'Owning Entity GEMS ID': {0: 23455,
                  1: 23539,
                  2: 23460,
                  3: 10118,
                  4: 10104,
                  5: 10029,
                  6: 50451,
                  7: 10050,
                  8: 0,
                  9: 0,
                  10: 0,
                  11: 0,
                  12: 0},
                 'Category': {0: 'ModCo',
                  1: 'ModCo',
                  2: 'ModCo',
                  3: 'LPT',
                  4: 'LPT',
                  5: 'LPT',
                  6: 'Surplus',
                  7: 'ALBA',
                  8: 'ModCo',
                  9: 'ModCo',
                  10: 'LPT',
                  11: 'ModCo',
                  12: 'ModCo'}}

#%%                 
Rating = {'NAIC Rating': {0: '1',
          1: '1',
          2: '1',
          3: '1-',
          4: '1-',
          5: '1=',
          6: '1=',
          7: '1AM',
          8: '1AM',
          9: '1AM',
          10: '1FE',
          11: '1FE',
          12: '1FE',
          13: '1FE',
          14: '1FM',
          15: '1FM',
          16: '1FM',
          17: '1FM',
          18: '1FM',
          19: '1FM',
          20: '1FM',
          21: '1FM',
          22: '1FM',
          23: '1FM',
          24: '1PL',
          25: '1PL',
          26: '1PL',
          27: '1Z',
          28: '1Z',
          29: '2-',
          30: '2+',
          31: '2=',
          32: '2AM',
          33: '2FE',
          34: '2FE',
          35: '2FE',
          36: '2FM',
          37: '2FM',
          38: '2FM',
          39: '2FM',
          40: '2PL',
          41: '2S-',
          42: '2Z',
          43: '3+',
          44: '3AM',
          45: '3AM',
          46: '3FE',
          47: '3FE',
          48: '3FE',
          49: '3FM',
          50: '3FM',
          51: '3FM',
          52: '3PL',
          53: '3PL',
          54: '4-',
          55: '4AM',
          56: '4FE',
          57: '4FE',
          58: '4FE',
          59: '4FM',
          60: '4FM',
          61: '4Z',
          62: '5FE',
          63: '5FE',
          64: '5FM',
          65: '5GI',
          66: '5Z',
          67: '6',
          68: '6FE',
          69: '6FE',
          70: '6FE',
          71: '6FE',
          72: '6FM',
          73: '6FM',
          74: '6FM',
          75: '6FM',
          76: '6PL',
          77: 'L',
          78: 'RP1FE',
          79: 'RP1VFE',
          80: 'SOURCE UNDEFINED',
          81: 'SOURCE UNDEFINED',
          82: 'SOURCE UNDEFINED',
          83: 'SOURCE UNDEFINED',
          84: 'SOURCE UNDEFINED',
          85: 'Z',
          86: '5FM'},
         'AIG Derived Rating': {0: 'AA',
          1: 'AAA',
          2: 'BBB',
          3: 'A',
          4: 'AA',
          5: 'AA',
          6: 'BBB',
          7: 'AA',
          8: 'BBB',
          9: 'BBB',
          10: 'A',
          11: 'AA',
          12: 'AAA',
          13: 'BBB',
          14: 'A',
          15: 'AA',
          16: 'AAA',
          17: 'B',
          18: 'BB',
          19: 'BBB',
          20: 'C',
          21: 'CC',
          22: 'CCC',
          23: 'D',
          24: 'A',
          25: 'AA',
          26: 'AAA',
          27: 'A',
          28: 'AA',
          29: 'BBB',
          30: 'BBB',
          31: 'BBB',
          32: 'BBB',
          33: 'A',
          34: 'BB',
          35: 'BBB',
          36: 'BBB',
          37: 'CC',
          38: 'CCC',
          39: 'D',
          40: 'BBB',
          41: 'BBB',
          42: 'BBB',
          43: 'BB',
          44: 'BB',
          45: 'BBB',
          46: 'B',
          47: 'BB',
          48: 'BBB',
          49: 'BB',
          50: 'CCC',
          51: 'D',
          52: 'BB',
          53: 'BBB',
          54: 'B',
          55: 'B',
          56: 'B',
          57: 'BB',
          58: 'CCC',
          59: 'B',
          60: 'CCC',
          61: 'B',
          62: 'CCC',
          63: 'D',
          64: 'CCC',
          65: 'CCC',
          66: 'CCC',
          67: 'C',
          68: 'BBB',
          69: 'C',
          70: 'CC',
          71: 'D',
          72: 'C',
          73: 'CC',
          74: 'CCC',
          75: 'D',
          76: 'BBB',
          77: None,
          78: 'AA',
          79: 'AA',
          80: 'A',
          81: 'AA',
          82: 'B',
          83: 'BBB',
          84: None,
          85: None,
          86: 'CC'},
         'Derived Rating Modified': {0: 'AA',
          1: 'AAA',
          2: 'A',
          3: 'A',
          4: 'AA',
          5: 'AA',
          6: 'A',
          7: 'AA',
          8: 'A',
          9: 'A',
          10: 'A',
          11: 'AA',
          12: 'AAA',
          13: 'A',
          14: 'A',
          15: 'AA',
          16: 'AAA',
          17: 'A',
          18: 'A',
          19: 'A',
          20: 'A',
          21: 'A',
          22: 'A',
          23: 'A',
          24: 'A',
          25: 'AA',
          26: 'AAA',
          27: 'A',
          28: 'AA',
          29: 'BBB',
          30: 'BBB',
          31: 'BBB',
          32: 'BBB',
          33: 'BBB',
          34: 'BBB',
          35: 'BBB',
          36: 'BBB',
          37: 'BBB',
          38: 'BBB',
          39: 'BBB',
          40: 'BBB',
          41: 'BBB',
          42: 'BBB',
          43: 'BB',
          44: 'BB',
          45: 'BB',
          46: 'BB',
          47: 'BB',
          48: 'BB',
          49: 'BB',
          50: 'BB',
          51: 'BB',
          52: 'BB',
          53: 'BB',
          54: 'B',
          55: 'B',
          56: 'B',
          57: 'B',
          58: 'B',
          59: 'B',
          60: 'B',
          61: 'B',
          62: 'CCC',
          63: 'CCC',
          64: 'CCC',
          65: 'CCC',
          66: 'CCC',
          67: 'CC',
          68: 'CC',
          69: 'CC',
          70: 'CC',
          71: 'CC',
          72: 'CC',
          73: 'CC',
          74: 'CC',
          75: 'CC',
          76: 'CC',
          77: 'A',
          78: 'AA',
          79: 'A',
          80: 'NA-BBB',
          81: 'NA-BBB',
          82: 'NA-BBB',
          83: 'NA-BBB',
          84: 'NA-BBB',
          85: 'A',
          86: 'CCC'}}